### ISSUE TITLE
Add "Topology"

### ISSUE THREAD

**Issue by q-inho** [QuantumComputingKorea/Quantum-Computing-Glossary#1]
# Term: Topology

> `New Term` 
 ------------
## Suggested Translation: 
위상

### Details (optional): 
[양자백서] topological cluster state => 위상 클러스터 상태
[양자백서] topological order => 위상론적 질서
위상/위상 구조=phase, 위상수학=topology

--------------
## Source: 
https://qiskit.org/documentation/stable/0.24/qc_intro.html

**Comment by glingi** [comment]
전자공학에서 전자 회로의 전체적인 구조를 논할때 많이 봤던 단어네요.

아래 홈페이지에서는 토폴로지 그대로 쓰거나 네트워크 구성 형태 / 형상 이라고 하는군요.
`http://www.ktword.co.kr/test/view/view.php?nav=2&no=356&sh=Topology`

IBM 백엔드 속성에서도 보면 토폴로지를 다음과 같이 설명하네요.

Topology diagram - A diagram that indicates the pairs of qubits that support two-qubit gate operations between them. This is also called the coupling map or connectivity. Qubits are represented as circles and the supported two-qubit gate operations are displayed as lines connecting the qubits.
`https://quantum-computing.ibm.com/lab/docs/iql/manage/systems/configuration`
