### ISSUE TITLE
Add "Quantum Walk"

### ISSUE THREAD

**Issue by glingi** [QuantumComputingKorea/Quantum-Computing-Glossary#11]
# Term: Word

> `Current Term`
 ------------
## Suggested Translation: 
1. 양자 걸음
2. 양자 보행

### Details(optional): 

--------------
## Source: https://gitlocalize.com/repo/7494/ko/notebooks/ch-algorithms/quantum-walk-search-algorithm.ipynb

**Comment by q-inho** [comment]
TTA정보통신용어집에서는 quantum walk을 `양자걸음`이라고 번역이 되어 있습니다.
http://word.tta.or.kr/dictionary/dictionaryView.do?word_seq=061317-1

**Comment by Denny-Hwang** [comment]
그러면 일단 양자걸음이라고 해도 괜찮을 것 같습니다

**Comment by q-inho** [comment]
그러면 양자걸음으로 사전에 추가하겠습니다.
