### ISSUE TITLE
Add "Extrapolator"

### ISSUE THREAD

**Issue by q-inho** [QuantumComputingKorea/Quantum-Computing-Glossary#2]
# Term: Extrapolator

> `New Term`
 ------------
## Suggested Translation: 
외삽기
보외기

### Details(optional): 
extrapolation은 외삽법 혹은 보외법으로 번역할 수 있는데.... 여기서 extrapolator는... 외삽기 혹은 보외기로 하자니 너무 어색해서... 좋은 의견 있으시면 주세요!

https://ko.wikipedia.org/wiki/%EB%B3%B4%EC%99%B8%EB%B2%95

--------------
## Source: 
https://qiskit.org/documentation/nature/tutorials/05_Sampling_potential_energy_surfaces.html

**Comment by Denny-Hwang** [comment]
어렵네요.... 번역해도 한자라서.... 
interpolation/extrapolation을...
보외/보간 조합보다는 내삽/외삽으로 번역하는 것이 조금 더 나은 것 같다는 의견 드립니다. 
딱히 레퍼런스는 없이 경험적이지만요....
