### ISSUE TITLE
Add "Orthonormal Basis"

### ISSUE THREAD

**Issue by q-inho** [QuantumComputingKorea/Quantum-Computing-Glossary#7]
# Term: Orthonormal Basis

> `New Term`
 ------------
## Suggested Translation: 
정규 직교 기저

### Details(optional): 
Orthonormal basis의 wikipedia 한글 문서: https://ko.wikipedia.org/wiki/%EC%A0%95%EA%B7%9C_%EC%A7%81%EA%B5%90_%EA%B8%B0%EC%A0%80

--------------
## Source: 
https://github.com/Qiskit/platypus/blob/main/notebooks/ch-states/representing-qubit-states.ipynb

**Comment by Denny-Hwang** [comment]
'정규 직교 기저' 좋습니다!
