### ISSUE TITLE
Add "Global Phase"

### ISSUE THREAD

**Issue by q-inho** [QuantumComputingKorea/Quantum-Computing-Glossary#8]
# Term: Global Phase

> `New Term`
 ------------
## Suggested Translation: 
-전체적 위상
-글로벌 위상

### Details(optional): 
한국정보화진흥원과 한국전자통신연구원을 출처로 웹수집한 네이버 사전으로는 전체적 위상이라고 번역이 되어있지만 웹수집으로 얻은 정보이므로 확실하지 않습니다.
https://en.dict.naver.com/#/entry/enko/d878745cbbb1469db2bebf066d0ca40f

--------------
## Source: 
https://github.com/Qiskit/platypus/blob/main/notebooks/ch-states/representing-qubit-states.ipynb

**Comment by Denny-Hwang** [comment]
'전역 위상'이라고 번역하는게 좋을 것 같습니다
